// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PullRequestStatus string

const (
	PullRequestStatusOpen   PullRequestStatus = "open"
	PullRequestStatusMerged PullRequestStatus = "merged"
)

func (e *PullRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PullRequestStatus(s)
	case string:
		*e = PullRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PullRequestStatus: %T", src)
	}
	return nil
}

type NullPullRequestStatus struct {
	PullRequestStatus PullRequestStatus `json:"pull_request_status"`
	Valid             bool              `json:"valid"` // Valid is true if PullRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PullRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PullRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PullRequestStatus), nil
}

type PullRequest struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	AuthorID  uuid.UUID          `db:"author_id" json:"author_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Status    string             `db:"status" json:"status"`
	MergedAt  pgtype.Timestamptz `db:"merged_at" json:"merged_at"`
}

type PullRequestReviewer struct {
	PullRequestID uuid.UUID `db:"pull_request_id" json:"pull_request_id"`
	ReviewerID    uuid.UUID `db:"reviewer_id" json:"reviewer_id"`
}

type Team struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

type TeamUser struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type User struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	Active bool      `db:"active" json:"active"`
}
