DROP TABLE IF EXISTS pull_request_reviewer;
DROP TABLE IF EXISTS pull_request;
DROP TABLE IF EXISTS team_user;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS "user";

DROP EXTENSION IF EXISTS "uuid-ossp";
