// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_request.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPullRequest = `-- name: CreatePullRequest :exec
INSERT INTO pull_request (id, title, author_id, created_at, status, merged_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePullRequestParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	AuthorID  uuid.UUID          `db:"author_id" json:"author_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Status    string             `db:"status" json:"status"`
	MergedAt  pgtype.Timestamptz `db:"merged_at" json:"merged_at"`
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) error {
	_, err := q.db.Exec(ctx, createPullRequest,
		arg.ID,
		arg.Title,
		arg.AuthorID,
		arg.CreatedAt,
		arg.Status,
		arg.MergedAt,
	)
	return err
}

const deletePullRequest = `-- name: DeletePullRequest :exec
DELETE FROM pull_request
WHERE id = $1
`

func (q *Queries) DeletePullRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePullRequest, id)
	return err
}

const getPullRequest = `-- name: GetPullRequest :one
SELECT id, title, author_id, created_at, status, merged_at FROM pull_request WHERE id = $1
`

func (q *Queries) GetPullRequest(ctx context.Context, id uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequest, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.CreatedAt,
		&i.Status,
		&i.MergedAt,
	)
	return i, err
}

const getPullRequests = `-- name: GetPullRequests :many
SELECT id, title, author_id, created_at, status, merged_at FROM pull_request
`

func (q *Queries) GetPullRequests(ctx context.Context) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, getPullRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequest{}
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.CreatedAt,
			&i.Status,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePullRequest = `-- name: UpdatePullRequest :exec
UPDATE pull_request
SET title = $2, author_id = $3, created_at = $4, status = $5, merged_at = $6
WHERE id = $1
`

type UpdatePullRequestParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	AuthorID  uuid.UUID          `db:"author_id" json:"author_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Status    string             `db:"status" json:"status"`
	MergedAt  pgtype.Timestamptz `db:"merged_at" json:"merged_at"`
}

func (q *Queries) UpdatePullRequest(ctx context.Context, arg UpdatePullRequestParams) error {
	_, err := q.db.Exec(ctx, updatePullRequest,
		arg.ID,
		arg.Title,
		arg.AuthorID,
		arg.CreatedAt,
		arg.Status,
		arg.MergedAt,
	)
	return err
}

const updatePullRequestStatus = `-- name: UpdatePullRequestStatus :exec
UPDATE pull_request
SET status = $2, merged_at = $3
WHERE id = $1
`

type UpdatePullRequestStatusParams struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	Status   string             `db:"status" json:"status"`
	MergedAt pgtype.Timestamptz `db:"merged_at" json:"merged_at"`
}

func (q *Queries) UpdatePullRequestStatus(ctx context.Context, arg UpdatePullRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updatePullRequestStatus, arg.ID, arg.Status, arg.MergedAt)
	return err
}
