// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_request_reviewer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addReviewerToPullRequest = `-- name: AddReviewerToPullRequest :exec
INSERT INTO pull_request_reviewer (pull_request_id, reviewer_id)
VALUES ($1, $2)
`

type AddReviewerToPullRequestParams struct {
	PullRequestID uuid.UUID `db:"pull_request_id" json:"pull_request_id"`
	ReviewerID    uuid.UUID `db:"reviewer_id" json:"reviewer_id"`
}

func (q *Queries) AddReviewerToPullRequest(ctx context.Context, arg AddReviewerToPullRequestParams) error {
	_, err := q.db.Exec(ctx, addReviewerToPullRequest, arg.PullRequestID, arg.ReviewerID)
	return err
}

const getPullRequestReviewers = `-- name: GetPullRequestReviewers :many
SELECT reviewer_id FROM pull_request_reviewer WHERE pull_request_id = $1
`

func (q *Queries) GetPullRequestReviewers(ctx context.Context, pullRequestID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getPullRequestReviewers, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var reviewer_id uuid.UUID
		if err := rows.Scan(&reviewer_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReviewerFromPullRequest = `-- name: RemoveReviewerFromPullRequest :exec
DELETE FROM pull_request_reviewer
WHERE pull_request_id = $1 AND reviewer_id = $2
`

type RemoveReviewerFromPullRequestParams struct {
	PullRequestID uuid.UUID `db:"pull_request_id" json:"pull_request_id"`
	ReviewerID    uuid.UUID `db:"reviewer_id" json:"reviewer_id"`
}

func (q *Queries) RemoveReviewerFromPullRequest(ctx context.Context, arg RemoveReviewerFromPullRequestParams) error {
	_, err := q.db.Exec(ctx, removeReviewerFromPullRequest, arg.PullRequestID, arg.ReviewerID)
	return err
}
