// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_request_reviewer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPullRequestReviewer = `-- name: CreatePullRequestReviewer :exec
INSERT INTO pull_request_reviewer (pull_request_id, reviewer_id)
VALUES ($1, $2)
`

type CreatePullRequestReviewerParams struct {
	PullRequestID uuid.UUID `db:"pull_request_id" json:"pull_request_id"`
	ReviewerID    uuid.UUID `db:"reviewer_id" json:"reviewer_id"`
}

func (q *Queries) CreatePullRequestReviewer(ctx context.Context, arg CreatePullRequestReviewerParams) error {
	_, err := q.db.Exec(ctx, createPullRequestReviewer, arg.PullRequestID, arg.ReviewerID)
	return err
}

const deletePullRequestReviewer = `-- name: DeletePullRequestReviewer :exec
DELETE FROM pull_request_reviewer
WHERE pull_request_id = $1 AND reviewer_id = $2
`

type DeletePullRequestReviewerParams struct {
	PullRequestID uuid.UUID `db:"pull_request_id" json:"pull_request_id"`
	ReviewerID    uuid.UUID `db:"reviewer_id" json:"reviewer_id"`
}

func (q *Queries) DeletePullRequestReviewer(ctx context.Context, arg DeletePullRequestReviewerParams) error {
	_, err := q.db.Exec(ctx, deletePullRequestReviewer, arg.PullRequestID, arg.ReviewerID)
	return err
}

const deletePullRequestReviewersByPRID = `-- name: DeletePullRequestReviewersByPRID :exec
DELETE FROM pull_request_reviewer
WHERE pull_request_id = $1
`

func (q *Queries) DeletePullRequestReviewersByPRID(ctx context.Context, pullRequestID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePullRequestReviewersByPRID, pullRequestID)
	return err
}

const deletePullRequestReviewersByReviewerID = `-- name: DeletePullRequestReviewersByReviewerID :exec
DELETE FROM pull_request_reviewer
WHERE reviewer_id = $1
`

func (q *Queries) DeletePullRequestReviewersByReviewerID(ctx context.Context, reviewerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePullRequestReviewersByReviewerID, reviewerID)
	return err
}

const getPullRequestReviewerReviewerIDs = `-- name: GetPullRequestReviewerReviewerIDs :many
SELECT reviewer_id FROM pull_request_reviewer WHERE pull_request_id = $1
`

func (q *Queries) GetPullRequestReviewerReviewerIDs(ctx context.Context, pullRequestID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getPullRequestReviewerReviewerIDs, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var reviewer_id uuid.UUID
		if err := rows.Scan(&reviewer_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPullRequestsByReviewer = `-- name: GetPullRequestsByReviewer :many
SELECT pr.id, pr.title, pr.author_id, pr.status, pr.merged_at
FROM pull_request pr
JOIN pull_request_reviewer prr ON pr.id = prr.pull_request_id
WHERE prr.reviewer_id = $1
`

func (q *Queries) GetPullRequestsByReviewer(ctx context.Context, reviewerID uuid.UUID) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, getPullRequestsByReviewer, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequest{}
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Status,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
