// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddReviewerToPullRequest(ctx context.Context, arg AddReviewerToPullRequestParams) error
	AddUserToTeam(ctx context.Context, arg AddUserToTeamParams) error
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteTeam(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetPullRequest(ctx context.Context, id uuid.UUID) (PullRequest, error)
	GetPullRequestReviewers(ctx context.Context, pullRequestID uuid.UUID) ([]uuid.UUID, error)
	GetPullRequests(ctx context.Context) ([]PullRequest, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamByName(ctx context.Context, name string) (Team, error)
	GetTeams(ctx context.Context) ([]Team, error)
	GetTeamsForUser(ctx context.Context, userID uuid.UUID) ([]Team, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	GetUsersInTeam(ctx context.Context, teamID uuid.UUID) ([]User, error)
	RemoveReviewerFromPullRequest(ctx context.Context, arg RemoveReviewerFromPullRequestParams) error
	RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error
	UpdatePullRequestStatus(ctx context.Context, arg UpdatePullRequestStatusParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
