// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addUserToTeam = `-- name: AddUserToTeam :exec
INSERT INTO team_user (team_id, user_id)
VALUES ($1, $2)
`

type AddUserToTeamParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) AddUserToTeam(ctx context.Context, arg AddUserToTeamParams) error {
	_, err := q.db.Exec(ctx, addUserToTeam, arg.TeamID, arg.UserID)
	return err
}

const getTeamsForUser = `-- name: GetTeamsForUser :many
SELECT t.id, t.name
FROM team t
JOIN team_user tu ON t.id = tu.team_id
WHERE tu.user_id = $1
`

func (q *Queries) GetTeamsForUser(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInTeam = `-- name: GetUsersInTeam :many
SELECT u.id, u.name, u.active
FROM "user" u
JOIN team_user tu ON u.id = tu.user_id
WHERE tu.team_id = $1
`

func (q *Queries) GetUsersInTeam(ctx context.Context, teamID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTeam = `-- name: RemoveUserFromTeam :exec
DELETE FROM team_user
WHERE team_id = $1 AND user_id = $2
`

type RemoveUserFromTeamParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTeam, arg.TeamID, arg.UserID)
	return err
}
