// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeamUser = `-- name: CreateTeamUser :exec
INSERT INTO team_user (team_id, user_id)
VALUES ($1, $2)
`

type CreateTeamUserParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateTeamUser(ctx context.Context, arg CreateTeamUserParams) error {
	_, err := q.db.Exec(ctx, createTeamUser, arg.TeamID, arg.UserID)
	return err
}

const deleteTeamUsersByTeamID = `-- name: DeleteTeamUsersByTeamID :exec
DELETE FROM team_user
WHERE team_id = $1
`

func (q *Queries) DeleteTeamUsersByTeamID(ctx context.Context, teamID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamUsersByTeamID, teamID)
	return err
}

const getTeamForUser = `-- name: GetTeamForUser :one
SELECT t.id, t.name
FROM team t
JOIN team_user tu ON t.id = tu.team_id
WHERE tu.user_id = $1
`

func (q *Queries) GetTeamForUser(ctx context.Context, userID uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamForUser, userID)
	var i Team
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTeamIDForUser = `-- name: GetTeamIDForUser :one
SELECT t.id
FROM team t
JOIN team_user tu ON t.id = tu.team_id
WHERE tu.user_id = $1
`

func (q *Queries) GetTeamIDForUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTeamIDForUser, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserIDsInTeam = `-- name: GetUserIDsInTeam :many
SELECT user_id
FROM team_user
WHERE team_id = $1
`

func (q *Queries) GetUserIDsInTeam(ctx context.Context, teamID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserIDsInTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInTeam = `-- name: GetUsersInTeam :many
SELECT u.id, u.name, u.active
FROM "user" u
JOIN team_user tu ON u.id = tu.user_id
WHERE tu.team_id = $1
`

func (q *Queries) GetUsersInTeam(ctx context.Context, teamID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTeam = `-- name: RemoveUserFromTeam :exec
DELETE FROM team_user
WHERE team_id = $1 AND user_id = $2
`

type RemoveUserFromTeamParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTeam, arg.TeamID, arg.UserID)
	return err
}
